#dein.vim---------------

[[plugins]]
repo = 'Shougo/dein.vim'

#airline-----------------

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/airline.vim'

#airline-themes----------

[[plugins]]
repo = 'vim-airline/vim-airline-themes'


#defx.nvim---------------

#[[plugins]]
#repo = 'Shougo/defx.nvim'
#on_cmd = 'Defx'
#depends = ['defx-icons', 'defx-git']
#hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/defx_key.vim'


#defx-icon.nvim

#[[plugins]]
#repo = 'kristijanhusak/defx-icons'


#ryanoasis/vim-devicons---

#[[plugins]]
#repo = 'ryanoasis/vim-devicons'

#vim-quickrun

#[[plugins]]
#repo = 'thinca/vim-quickrun'
#hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/quickrun.vim'

#indentLine-----------------

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = 'source $XDG_CONFIG_HOME/nvim/plugins/indentLine.vim'


#colorsheme--------------
[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = 'source $XDG_CONFIG_HOME/nvim/colors/colorscheme.vim'

#markdown-preview----------
[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'previm/previm'
hook_add = '''
    autocmd BufRead,BufNewFile *.md  set filetype=markdown
    nnoremap <silent> <C-p> :PrevimOpen<CR>
    let g:vim_markdown_folding_disabled=1
    let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#wakatime----------
[[plugins]]
repo = 'wakatime/vim-wakatime'
