#vim-tex-----------------

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = 'source $XDG_CONFIG_HOME/nvim/ftplugin/tex.vim'

#jedi-vim----------------

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = 'source $XDG_CONFIG_HOME/nvim/ftplugin/python.vim'

#Go----------------------

[[plugins]]
repo = 'josa42/coc-go'
on_ft = ['go']

#C / C++ ----------------

[[plugins]]
repo = 'clangd/coc-clangd'
on_ft = ['c', 'cpp']
hook_sorce = '''
  hi link cStorageClass Statement 
  hi link cppStructure Statement
  hi link cppType Statement
'''

#javascript--------------

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['js']

#flutter-----------------

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = ['dart']

[[plugins]]
repo = 'thosakwe/vim-flutter'
on_ft = ['dart']
